name: nagstamon
base: core22 
version: git
summary: Nagstamon is a status monitor for the desktop.
description: |
  Nagstamon is a status monitor for the desktop. It connects to multiple Nagios, 
  Icinga, Opsview, Centreon, Op5 Monitor/Ninja, Checkmk Multisite, Thruk and 
  monitos monitoring servers. 
  
  Experimental support is provided for Zabbix, Zenoss and Livestatus monitors. 
  
  It resides in systray, as a floating statusbar or fullscreen at the desktop 
  showing a brief summary of critical, warning, unknown, unreachable and down 
  hosts and services. 

grade: devel 
confinement: devmode 

apps:
  nagstamon:
    command: nagstamon.py
    plugs: [home, network, desktop, audio-playback]

parts:
  nagstamon:
    plugin: python
    python-requirements:
    - build/requirements/linux.txt
    build-packages:
    - pkg-config
    - libdbus-1-dev
    - libglib2.0-dev
    - libkrb5-dev
    source: https://github.com/patrick-pt/nagstamon-snap.git

